on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-node:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/node
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-node
          path: packages/node/coverage